### ISSUE TITLE
No wgt file found

### ISSUE THREAD

**Issue by elrezad** [gardner/jellyfin-tizen-build#5]
Hi, I've followed the instructions; Installed docker, run sudo docker build (...) and docher run -v (...) but there's no wgt file in the output folder. What am I doing wrong?

Any help? Thanks

**Comment by elrezad** [comment]
I was able to build Jellyfin.wgt by entering into the docker file and running 
`tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"`
But when I try to send the file to the tv, it says 

> install failed[118, -12], reason: Check certificate error

**Comment by ecker00** [comment]
Was stumped on this too, but on my system turns out the `output` folder was created as root, while the build process runs as a user, so no output file could be written (But didn't see any errors for this either). Anyway, before running the build command, change ownership of the output folder.

Updated instructions:
```
docker build -t jellyfin-tizen-build .

sudo chown myuser:myuser output

docker run -v "$(pwd)/output":/output -it jellyfin-tizen-build

ls -lah output/
```

**Comment by gardner** [comment]
The README has been updated with these commans. Thanks
